language: python

cache: pip

python:
    - "3.8"

install:
    - pip install -r requirements.txt
    - python setup.py develop

script:
    - scripts/lint
    - scripts/test

after_script:
    - codecov
